// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPDAvPrSNwaZfSSg7tZ6UA9qWu1xblMM',
    appId: '1:199715081014:web:70fd179b675ae360298197',
    messagingSenderId: '199715081014',
    projectId: 'loginregister-5aed0',
    authDomain: 'loginregister-5aed0.firebaseapp.com',
    storageBucket: 'loginregister-5aed0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABOlJgET6yj93YEvHQ983_gQvvzX1iTAA',
    appId: '1:199715081014:android:b3b8d48ed00e497f298197',
    messagingSenderId: '199715081014',
    projectId: 'loginregister-5aed0',
    storageBucket: 'loginregister-5aed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjUC0jIeqo_laWVeFmAYlZO10NWhNuWpI',
    appId: '1:199715081014:ios:e9987f50d307a6fe298197',
    messagingSenderId: '199715081014',
    projectId: 'loginregister-5aed0',
    storageBucket: 'loginregister-5aed0.firebasestorage.app',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjUC0jIeqo_laWVeFmAYlZO10NWhNuWpI',
    appId: '1:199715081014:ios:e9987f50d307a6fe298197',
    messagingSenderId: '199715081014',
    projectId: 'loginregister-5aed0',
    storageBucket: 'loginregister-5aed0.firebasestorage.app',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPDAvPrSNwaZfSSg7tZ6UA9qWu1xblMM',
    appId: '1:199715081014:web:be68bd498cc29ef7298197',
    messagingSenderId: '199715081014',
    projectId: 'loginregister-5aed0',
    authDomain: 'loginregister-5aed0.firebaseapp.com',
    storageBucket: 'loginregister-5aed0.firebasestorage.app',
  );
}
